#### Zadanie 1 Metoda Gaussa-Jordana

Napisz i sprawdź funkcję rozwiązującą układ równań liniowych n × n metodą Gaussa-Jordana.
Dla rozmiarów macierzy współczynników większych niż 500 × 500 porównaj
czasy działania zaimplementowanej funkcji z czasami uzyskanymi dla wybranych funkcji
bibliotecznych.

In [1]:
import numpy as np
import math
import time

In [2]:
n = 500
A = np.random.rand(n, n)
b = np.random.rand(n)

In [3]:
A_matrix = np.matrix(A)
b_matrix = np.matrix(b)

In [4]:
def swap_rows(M, row1, row2):
    if len(M) == 1:
        M[0,[row1,row2]] = M[0,[row2,row1]]
    else:
        M[[row1,row2]] = M[[row2,row1]]

In [5]:
def solve_gauss_jordan(A, b):
    n = len(A)  
    for k in range(0,n):
        # Find pivot
        maxindex = abs(A[k:,k]).argmax() + k
        # Swap rows
        if maxindex != k:
            swap_rows(A, k, maxindex)
            swap_rows(b, k, maxindex)
        # Gauss eliminatation
        for row in range(k+1, n):
            m = A[row,k]/A[k,k]
            A[row, k:] = A[row, k:] - m*A[k, k:]
            b[0,row] = b[0,row] - m*b[0,k]
    # Back substitution
    x = np.zeros(n)
    for k in range(n-1, -1, -1):
        x[k] = (b[0,k] - np.dot(A[k,k+1:],x[k+1:]))/A[k,k]
    return np.matrix(x)

In [6]:
np_start = time.time()
x = np.linalg.solve(A, b)
np_end = time.time()
x

array([  2.58032294e-01,   2.48297480e-01,   8.34188076e-01,
         5.55624531e-02,  -1.40621186e+00,  -2.62640028e+00,
        -3.89303884e-01,  -5.93007779e-01,  -1.56227257e-01,
         1.83607310e+00,  -1.66270371e+00,   1.76597421e+00,
        -4.69418919e-01,  -1.09073998e-01,   1.97036650e-01,
         1.03333767e+00,   5.91069182e-01,  -2.83285984e+00,
         1.81963847e+00,  -6.00790278e-01,   5.62483919e-01,
        -7.82131946e-01,  -3.39818282e-01,  -1.86643293e-01,
         8.52168581e-01,   1.34361907e+00,   3.56943184e-01,
        -2.18581528e+00,  -1.48040458e+00,   2.93644389e+00,
         2.62944624e-01,   9.66783365e-01,   1.79817359e+00,
         1.44335022e-01,   2.75455703e-01,   6.16159919e-01,
        -1.15749735e+00,  -1.41906373e+00,   5.19073665e-01,
        -2.42856411e+00,  -1.09341930e+00,   6.77185716e-01,
         1.78535979e+00,   1.78587964e+00,  -5.24661545e-01,
         4.83089024e-02,  -1.42039816e+00,   1.05856971e+00,
         1.63694782e+00,

In [7]:
my_start = time.time()
x = solve_gauss_jordan(A_matrix, b_matrix)
my_end = time.time()
x

matrix([[  2.58032294e-01,   2.48297480e-01,   8.34188076e-01,
           5.55624531e-02,  -1.40621186e+00,  -2.62640028e+00,
          -3.89303884e-01,  -5.93007779e-01,  -1.56227257e-01,
           1.83607310e+00,  -1.66270371e+00,   1.76597421e+00,
          -4.69418919e-01,  -1.09073998e-01,   1.97036650e-01,
           1.03333767e+00,   5.91069182e-01,  -2.83285984e+00,
           1.81963847e+00,  -6.00790278e-01,   5.62483919e-01,
          -7.82131946e-01,  -3.39818282e-01,  -1.86643293e-01,
           8.52168581e-01,   1.34361907e+00,   3.56943184e-01,
          -2.18581528e+00,  -1.48040458e+00,   2.93644389e+00,
           2.62944624e-01,   9.66783365e-01,   1.79817359e+00,
           1.44335022e-01,   2.75455703e-01,   6.16159919e-01,
          -1.15749735e+00,  -1.41906373e+00,   5.19073665e-01,
          -2.42856411e+00,  -1.09341930e+00,   6.77185716e-01,
           1.78535979e+00,   1.78587964e+00,  -5.24661545e-01,
           4.83089024e-02,  -1.42039816e+00,   1.058569

In [8]:
print("Funkcja biblioteczna - czas wykonania:     ", np_end - np_start)
print("Funkcja zaimplementowana - czas wykonania: ", my_end - my_start)

Funkcja biblioteczna - czas wykonania:      0.024904489517211914
Funkcja zaimplementowana - czas wykonania:  3.944518804550171


#### Zadanie 2 Faktoryzacja LU
Napisz i sprawdź funkcję dokonującą faktoryzacji A = LU macierzy A. Zastosuj częściowe poszukiwanie elementu wiodącego oraz skalowanie

In [19]:
import scipy

In [27]:
def lu_factorization(A):
    n = len(A)
    
    L = np.zeros((n,n))
    L = np.matrix(L)
    for i in range(0,n):
        L[i,i] = 1

    U = np.zeros((n,n))
    U = np.matrix(U)
    for i in range(0,n):
        for j in range(0,n):
            U[i,j] = A[i,j]
            
            
    for i in range(0,n):
        # Find pivot
        maxindex = abs(A[i:,i]).argmax() + i
        # Swap rows
        if maxindex != i:
            swap_rows(A, i, maxindex)
            
        # Substraction
        for k in range(i+1, n):
            m = U[k,i]/(U[i,i])
            L[k,i] = m
            for j in range(i, n):
                U[k,j] -= m*U[i,j]
        
        for k in range(i+1, n):
            U[k,i] = 0

    return (L, U)

In [20]:
A = scipy.array([ [7, 3, -1, 2], [3, 8, 1, -4], [-1, 1, 4, -1], [2, -4, -1, 6] ])
P, L, U = scipy.linalg.lu(A)

In [21]:
L

array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.42857143,  1.        ,  0.        ,  0.        ],
       [-0.14285714,  0.21276596,  1.        ,  0.        ],
       [ 0.28571429, -0.72340426,  0.08982036,  1.        ]])

In [22]:
U

array([[ 7.        ,  3.        , -1.        ,  2.        ],
       [ 0.        ,  6.71428571,  1.42857143, -4.85714286],
       [ 0.        ,  0.        ,  3.55319149,  0.31914894],
       [ 0.        ,  0.        ,  0.        ,  1.88622754]])

In [28]:
A = np.matrix([ [7, 3, -1, 2], [3, 8, 1, -4], [-1, 1, 4, -1], [2, -4, -1, 6] ])
L, U = lu_factorization(A)

In [29]:
L

matrix([[ 1.        ,  0.        ,  0.        ,  0.        ],
        [ 0.42857143,  1.        ,  0.        ,  0.        ],
        [-0.14285714,  0.21276596,  1.        ,  0.        ],
        [ 0.28571429, -0.72340426,  0.08982036,  1.        ]])

In [30]:
U

matrix([[ 7.        ,  3.        , -1.        ,  2.        ],
        [ 0.        ,  6.71428571,  1.42857143, -4.85714286],
        [ 0.        ,  0.        ,  3.55319149,  0.31914894],
        [ 0.        ,  0.        ,  0.        ,  1.88622754]])